"""empty message

Revision ID: 65614b2511b3
Revises: 
Create Date: 2024-02-21 12:38:27.869659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65614b2511b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
